spring:
  profiles:
    active: dev   # dev profile? ??
  application:
    name: service-discovery
  config:
    import: configserver:http://localhost:8888
  cloud:
    config:
      profile: dev    # dev profile ?? ?? ??
      label: main