apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}-config
  labels:
    app: {{ .Chart.Name }}
    version: {{ .Chart.AppVersion | default "1.0" }}
data:
  application.yml: |
    server:
      port: {{ .Values.config.server.port | default 8000 }}
    spring:
      jwt:
        issuer: {{ .Values.config.spring.jwt.issuer | default "http://localhost" }}
        secret: ${JWT_SECRET}
      application:
        name: {{ .Chart.Name | default "apigateway-service" }}
      cloud:
        gateway:
          routes:
            # auth-service 라우팅
            - id: auth-service
              uri: {{ .Values.config.spring.cloud.gateway.routes.uri.auth | default "http://auth-service.auth-service.svc.cluster.local:80" }}
              predicates:
                - Path=/auth/**
                - Method=GET,POST,PATCH,DELETE
              filters:
                - RemoveRequestHeader=Cookie
            # user-service 라우팅
            - id: user-service
              uri: {{ .Values.config.spring.cloud.gateway.routes.uri.user | default "http://user-service.user-service.svc.cluster.local:80" }}
              predicates:
                - Path=/user/**
                - Method=GET,POST,PATCH,DELETE
              filters:
                - RemoveRequestHeader=Cookie
                - AuthorizationHeaderFilter
            # dashboard-service 라우팅 - public 경로 (인증 없음)
            - id: dashboard-service-public
              uri: {{ .Values.config.spring.cloud.gateway.routes.uri.dashboard | default "http://dashboard-service.dashboard-service.svc.cluster.local:80" }}
              predicates:
                - Path=/dashboard/post-drive
                - Method=POST
              filters:
                - RemoveRequestHeader=Cookie
            # dashboard-service 라우팅 - 나머지 경로 (인증 필터 적용)
            - id: dashboard-service
              uri: {{ .Values.config.spring.cloud.gateway.routes.uri.dashboard | default "http://dashboard-service.dashboard-service.svc.cluster.local:80" }}
              predicates:
                - Path=/dashboard/**
                - Method=GET,POST,PATCH,DELETE
              filters:
                - RemoveRequestHeader=Cookie
                - AuthorizationHeaderFilter
            # llm-service 라우팅
            - id: llm-service
              uri: {{ .Values.config.spring.cloud.gateway.routes.uri.llm | default "http://llm-service.llm-service.svc.cluster.local:80" }}
              predicates:
                - Path=/llm/**
                - Method=GET,POST,PATCH,DELETE
              filters:
                - RemoveRequestHeader=Cookie
                - AuthorizationHeaderFilter
            # reward-service 라우팅
            - id: reward-service
              uri: {{ .Values.config.spring.cloud.gateway.routes.uri.reward | default "http://reward-service.reward-service.svc.cluster.local:80" }}
              predicates:
                - Path=/reward/**
                - Method=GET,POST,PATCH,DELETE
              filters:
                - RemoveRequestHeader=Cookie
                - AuthorizationHeaderFilter
            # admin-service 라우팅
            - id: admin-service
              uri: {{ .Values.config.spring.cloud.gateway.routes.uri.admin | default "http://admin-service.admin-service.svc.cluster.local:80" }}
              predicates:
                - Path=/admin/**
                - Method=GET,POST,PATCH,DELETE
              filters:
                - RemoveRequestHeader=Cookie
                - AuthorizationHeaderFilter
            # analysis-service 라우팅
            - id: analysis-service
              uri: {{ .Values.config.spring.cloud.gateway.routes.uri.analysis | default "http://analysis-service.analysis-service.svc.cluster.local:80" }}
              predicates:
                - Path=/analysis/**
                - Method=GET,POST,PATCH,DELETE
              filters:
                - RemoveRequestHeader=Cookie
                - AuthorizationHeaderFilter
            # agent-service 라우팅
            - id: agent-service
              uri: {{ .Values.config.spring.cloud.gateway.routes.uri.agent | default "http://agent-service.agent-service.svc.cluster.local:80" }}
              predicates:
                - Path=/agent/**
                - Method=GET,POST,PATCH,DELETE
              filters:
                - RemoveRequestHeader=Cookie
                - AuthorizationHeaderFilter
    management:
      endpoints:
        web:
          exposure:
            include: "*"
      endpoint:
        gateway:
          enabled: true