apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}-config
  labels:
    app: {{ .Chart.Name }}
    version: {{ .Chart.AppVersion | default "1.0" }}
data:
  application.yml: |
    server:
      port: {{ .Values.config.server.port | default 8000 }}
    spring:
      jwt:
        issuer: {{ .Values.config.spring.jwt.issuer | default "http://localhost" }}
        secret: ${JWT_SECRET}
      application:
        name: {{ .Chart.Name | default "apigateway-service" }}
      cloud:
        gateway:
          routes:
            - id: auth-service
              uri: http://auth-service.auth-service.svc.cluster.local:80
              predicates:
                - Path=/auth/**
                - Method=GET,POST,PATCH,DELETE
              filters:
                - RemoveRequestHeader=Cookie
            - id: user-service
              uri: http://user-service.user-service.svc.cluster.local:80
              predicates:
                - Path=/user/**
                - Method=GET,POST,PATCH,DELETE
              filters:
                - RemoveRequestHeader=Cookie
            - id: dashboard-service
              uri: http://dashboard-service.dashboard-service.svc.cluster.local:80
              predicates:
                - Path=/dashboard/**
                - Method=GET,POST,PATCH,DELETE
              filters:
                - RemoveRequestHeader=Cookie
            - id: llm-service
              uri: http://llm-service.llm-service.svc.cluster.local:80
              predicates:
                - Path=/llm/**
                - Method=GET,POST,PATCH,DELETE
              filters:
                - RemoveRequestHeader=Cookie
            - id: reward-service
              uri: http://reward-service.reward-service.svc.cluster.local:80
              predicates:
                - Path=/reward/**
                - Method=GET,POST,PATCH,DELETE
              filters:
                - RemoveRequestHeader=Cookie
            - id: admin-service
              uri: http://admin-service.admin-service.svc.cluster.local:80
              predicates:
                - Path=/admin/**
                - Method=GET,POST,PATCH,DELETE
              filters:
                - RemoveRequestHeader=Cookie
            - id: analysis-service
              uri: http://analysis-service.analysis-service.svc.cluster.local:80
              predicates:
                - Path=/analysis/**
                - Method=GET,POST,PATCH,DELETE
              filters:
                - RemoveRequestHeader=Cookie

    management:
      endpoints:
        web:
          exposure:
            include: "*"
      endpoint:
        gateway:
          enabled: true