replicaCount: 1

image:
  repository: 026274465258.dkr.ecr.ap-northeast-2.amazonaws.com/api-gateway-service
  tag: 20250609-21caf6a
  pullPolicy: IfNotPresent    # 이미지 가져오는 정책 로컬에 없을 때만 pull

service:
  type: ClusterIP   # 클러스터 내부에서만 접근 가능 (기본값)
  port: 80        

# 헬스체크 설정 (권장)
healthCheck:
  enabled: true
  path: /actuator/health
  port: 8000
  initialDelaySeconds: 60
  periodSeconds: 10

config:
  server:
    port: 8000
  spring:
    jwt:
      issuer: http://localhost
    cloud:
      gateway:
        routes:
          uri:
            auth: http://auth-service.auth-service.svc.cluster.local:80
            user: http://user-service.user-service.svc.cluster.local:80
            dashboard: http://dashboard-service.dashboard-service.svc.cluster.local:80
            llm: http://llm-service.llm-service.svc.cluster.local:80
            reward: http://reward-service.reward-service.svc.cluster.local:80
            admin: http://admin-service.admin-service.svc.cluster.local:80
            analysis: http://analysis-service.analysis-service.svc.cluster.local:80
            agent: http://agent-service.agent-service.svc.cluster.local:80