name: Build, Push to ECR and Deploy

on:
  push:
    branches:
     - main

env:
  AWS_REGION: ap-northeast-2
  APIGATEWAY_REPOSIROTY_URI: 026274465258.dkr.ecr.ap-northeast-2.amazonaws.com/api-gateway-service

jobs:
  build-push:
    name: Build and Push Docker Images
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: write

    steps:
      # 소스코드 체크아웃
      - name: Checkout source code
        uses: actions/checkout@v4

      # AWS 자격 증명 구성
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      # ECR 로그인
      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2
        
      # 이미지 태그 달기 
      - name: Set IMAGE_TAG
        run: |
          echo "IMAGE_TAG=$(date +'%Y%m%d')-${GITHUB_SHA::7}" >> $GITHUB_ENV

      # 모든 서비스 도커 이미지 빌드 및 ECR 푸시
      - name: Build and push Docker images for all services
        run: |
          echo "Building image for apigateway-service"
          docker build -t apigateway-service:${{ env.IMAGE_TAG }} ./apigateway-service
          docker tag apigateway-service:${{ env.IMAGE_TAG }} ${{ env.APIGATEWAY_REPOSIROTY_URI }}:${{ env.IMAGE_TAG }}
          docker push ${{ env.APIGATEWAY_REPOSIROTY_URI }}:${{ env.IMAGE_TAG }}
          
      - name: Update image tag in Helm values.yaml
        run: |
          sed -i "s/^[[:space:]]*tag:[[:space:]].*/  tag: ${{ env.IMAGE_TAG }}/" ./apigateway-service/values.yaml

          git config --global user.email "ci@github.com"
          git config --global user.name "GitHub Actions"
          
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
          
          
          git add ./apigateway-service/values.yaml
          
          git commit -m "chore: update image tag to ${{ env.IMAGE_TAG }}"
          git push origin HEAD:${{ github.ref }}
