name: Deploy to EC2

# 이 워크플로우는 "Build and Push to ECR" 작업이 완료되었을 때 자동으로 실행됨
on: 
  workflow_run:
    workflows: ["Build and Push to ECR"]  # 'Build and Push to ECR' 워크플로우가 완료되면 실행
    types:
      - completed  # 완료된 이벤트에만 반응

jobs:
  deploy:
    name: Deploy Container with CodeDeploy
    runs-on: ubuntu-latest  # 최신 우분투 러너 사용

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4  # 깃허브 레포지토리 코드 가져오기

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2  # AWS 인증 설정
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}  # 사용할 IAM Role
          aws-region: ap-northeast-2  # AWS 리전

      - name: Prepare deployment package
        run: |
          mkdir deploy-package  # 배포할 파일을 담을 디렉토리 생성
          cp appspec.yml deploy-package/  # appspec.yml 복사
          mkdir -p deploy-package/scripts  # 스크립트 디렉토리 생성
          cp scripts/deploy.sh deploy-package/scripts/  # deploy.sh 복사

      - name: Zip deployment package
        run: |
          cd deploy-package
          zip -r ../app.zip .  # 배포용 파일을 zip 압축

      - name: Upload deployment package to S3
        run: |
          aws s3 cp app.zip s3://${{ secrets.S3_BUCKET }}/app.zip  # 압축된 배포 파일을 S3 버킷에 업로드

      - name: Trigger deployment with CodeDeploy
        run: |
          aws deploy create-deployment \
            --application-name ${{ secrets.CODEDEPLOY_APP_NAME }} \  # CodeDeploy 애플리케이션 이름
            --deployment-group-name ${{ secrets.CODEDEPLOY_DEPLOYMENT_GROUP_NAME }} \  # 배포 그룹 이름
            --s3-location bucket=${{ secrets.S3_BUCKET }},key=app.zip,bundleType=zip  # S3에 있는 zip 파일로 배포 시작