name: Deploy to EC2

# 이 워크플로우는 "Build and Push to ECR" 작업이 완료되었을 때 자동으로 실행됨
on: 
  workflow_run:
    workflows: ["Build and Push to ECR"]
    types:
      - completed

# 배포 작업 정의
jobs:
  deploy:
    name: Deploy services to EC2
    runs-on: ubuntu-latest

    steps:
      # SSH를 사용해 EC2 서버에 접속하고 배포 스크립트를 실행
      - name: Connect and deploy on EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            # ECR에 로그인
            echo "Logging in to ECR"
            aws ecr get-login-password --region ap-northeast-2 | docker login --username AWS --password-stdin 211125408736.dkr.ecr.ap-northeast-2.amazonaws.com

            # 최신 Docker 이미지를 ECR에서 pull
            echo "Pulling images"
            docker pull 211125408736.dkr.ecr.ap-northeast-2.amazonaws.com/modive/apigateway-service:${{ github.sha }}
            docker pull 211125408736.dkr.ecr.ap-northeast-2.amazonaws.com/modive/config-service:${{ github.sha }}
            docker pull 211125408736.dkr.ec r.ap-northeast-2.amazonaws.com/modive/service-discovery:${{ github.sha }}

            # 기존 컨테이너를 중지하고 제거
            echo "Stopping existing containers"
            docker stop apigateway-service || true && docker rm apigateway-service || true
            docker stop config-service || true && docker rm config-service || true 
            docker stop service-discovery || true && docker rm service-discovery || true

            # 새로운 컨테이너를 실행
            echo "Running new containers"
            docker run -d --name apigateway-service -p 8000:8000 211125408736.dkr.ecr.ap-northeast-2.amazonaws.com/modive/apigateway-service:${{ github.sha }}
            docker run -d --name config-service -p 8888:8888 211125408736.dkr.ecr.ap-northeast-2.amazonaws.com/modive/config-service:${{ github.sha }}
            docker run -d --name service-discovery -p 8761:8761 211125408736.dkr.ecr.ap-northeast-2.amazonaws.com/modive/service-discovery:${{ github.sha }}